import type { GetStaticProps } from "next";
import Head from "next/head";
import { HeroSection } from "../components/HeroSection";
import {
  HomePageData,
  AboutUsPageData,
  ServicesPageData,
  OurTeamPageData,
  OurVolunteersPageData,
  DonatePageData,
} from "../data";
import { LowerHeader } from "../components/LowerHeader";
import { FrameSection } from "../components/FrameSection";
import { Numbers } from "../components/Numbers";
import { VideoSection } from "../components/VideoSection";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { NewsSection } from "../components/NewsSection";
import { ServicesSection } from "../components/ServicesSection";
import { PartnerSection } from "../components/PartnersSection";
// import { VolunteerComponent } from "../components/Volunteers";
// import ServicePageComponent from "../components/SvcPageSection";
// import { OurTeam } from "../components/OurTeam";

interface Props {
  homepage: HomePageData;
  newssection: HomePageData;
  servicessection: HomePageData;
  partnersection: HomePageData;
  aboutsection: AboutUsPageData;
  kriksection: AboutUsPageData;
  faqsection: AboutUsPageData;
  servicesPage: ServicesPageData; // Corrected property name
  svcsblockPage: ServicesPageData;
  ourteamPage: OurTeamPageData;
  volunteersData: OurVolunteersPageData;
  donateSection: DonatePageData;
}
const Home = ({
  homepage,
  newssection,
  servicessection,
  partnersection,
  // aboutsection,
  // kriksection,
  // faqsection,
  servicesPage,
  ourteamPage,
}: // volunteersData,
Props) => {
  return (
    <>
      <Head>
        <title>KRIK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <LowerHeader />
      <HeroSection heroData={homepage} />
      <FrameSection />
      <Numbers />
      <VideoSection />
      <NewsSection newsSectionData={newssection} />
      <ServicesSection servicesData={servicessection} />
      <PartnerSection partnersData={partnersection} />
      {/* <ServicePageComponent servicesPage={servicesPage} />
      <OurTeam ourteamPage={ourteamPage}/> */}
      {/* <VolunteerComponent volunteersData={volunteersData} /> */}
      <Footer />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const bannerDataRes = await fetch(
    "https://db-json-three.vercel.app/HomePage"
  );
  const bannerData: HomePageData = await bannerDataRes.json();

  const newsSectionDataRes = await fetch(
    "https://db-json-three.vercel.app/HomePage"
  );
  const newsSectionData: HomePageData = await newsSectionDataRes.json();

  const servicesSectionDataRes = await fetch(
    "https://db-json-three.vercel.app/HomePage"
  );
  const servicesData: HomePageData = await servicesSectionDataRes.json();

  const partnersSectionDataRes = await fetch(
    "https://db-json-three.vercel.app/HomePage"
  );
  const partnersData: HomePageData = await partnersSectionDataRes.json();

  const aboutUsSectionDataRes = await fetch(
    "https://db-json-three.vercel.app/AboutPage"
  );
  const aboutUsData: AboutUsPageData = await aboutUsSectionDataRes.json();

  const krikSectionDataRes = await fetch(
    "https://db-json-three.vercel.app/AboutPage"
  );
  const krikSData: AboutUsPageData = await krikSectionDataRes.json();

  const faQstSectionDataRes = await fetch(
    "https://db-json-three.vercel.app/AboutPage"
  );
  const faqSData: AboutUsPageData = await faQstSectionDataRes.json();

  const serviceSectionPageDataRes = await fetch(
    "https://db-json-three.vercel.app/ServicesPage"
  );
  const servicesPage: ServicesPageData = await serviceSectionPageDataRes.json();

  const svcsBlockPageDataRes = await fetch(
    "https://db-json-three.vercel.app/ServicesPage"
  );
  const svcsblockPage: ServicesPageData = await svcsBlockPageDataRes.json();

  const ourteamSectionPageDataRes = await fetch(
    "https://db-json-three.vercel.app/OurTeamPage"
  );
  const ourteamPageData: OurTeamPageData =
    await ourteamSectionPageDataRes.json();

  const ourvolunteerTeamPageDataRes = await fetch(
    "https://db-json-three.vercel.app/VolunteerPage"
  );
  const ourvolunteerTeamData: OurVolunteersPageData =
    await ourvolunteerTeamPageDataRes.json();

  const donateDataRes = await fetch("https://db-json-three.vercel.app/DonatePage");
  const donateSection: DonatePageData = await donateDataRes.json();

  return {
    props: {
      homepage: bannerData,
      newssection: newsSectionData,
      servicessection: servicesData,
      partnersection: partnersData,
      aboutsection: aboutUsData,
      kriksection: krikSData,
      faqsection: faqSData,
      servicesPage: servicesPage,
      svcsblockPage: svcsblockPage,
      ourteamPage: ourteamPageData,
      volunteersData: ourvolunteerTeamData,
      donateSection, 
    },
  };
};
